In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
print("Akash Maurya")

Akash Maurya

In [ ]:
from datasets import load_dataset

In [ ]:
ds = load_dataset("cornell-movie-review-data/rotten_tomatoes")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/7.46k [00:00<?, ?B/s]

train.parquet: reconstructing file:   0%|          |  0.00B /  699kB

train.parquet: downloading bytes:           |  0.00B

validation.parquet: reconstructing file:   0%|          |  0.00B / 90.0kB

validation.parquet: downloading bytes:           |  0.00B

test.parquet: reconstructing file:   0%|          |  0.00B / 92.2kB

test.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(ds["train"])

In [ ]:
df.head()

                                                text  label
0  the rock is destined to be the 21st century's ...      1
1  the gorgeously elaborate continuation of " the...      1
2                     effective but too-tepid biopic      1
3  if you sometimes like to go to the movies to h...      1
4  emerges as something rare , an issue movie tha...      1

In [ ]:
df.shape

(8530, 2)

In [ ]:
df.columns

Index(['text', 'label'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8530 entries, 0 to 8529
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    8530 non-null   object
 1   label   8530 non-null   int64
dtypes: int64(1), object(1)
memory usage: 133.4+ KB

In [ ]:
df["label"].value_counts()

label
1    4265
0    4265
Name: count, dtype: int64

In [ ]:
df["text"].head(10)

0    the rock is destined to be the 21st century's ...
1    the gorgeously elaborate continuation of " the...
2                       effective but too-tepid biopic
3    if you sometimes like to go to the movies to h...
4    emerges as something rare , an issue movie tha...
5    the film provides some great insight into the ...
6    offers that rare combination of entertainment ...
7    perhaps no picture ever made has more literall...
8    steers turns in a snappy screenplay that curls...
9    take care of my cat offers a refreshingly diff...
Name: text, dtype: object

In [ ]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df["text"] = df["text"].str.lower()

In [ ]:
  df["text"] = df["text"].str.strip()

In [ ]:
df["text"].head()

0    the rock is destined to be the 21st century's ...
1    the gorgeously elaborate continuation of " the...
2                       effective but too-tepid biopic
3    if you sometimes like to go to the movies to h...
4    emerges as something rare , an issue movie tha...
Name: text, dtype: object

In [ ]:
X = df["text"]
y = df["label"]

In [ ]:
print(X)

0       the rock is destined to be the 21st century's ...
1       the gorgeously elaborate continuation of " the...
2                          effective but too-tepid biopic
3       if you sometimes like to go to the movies to h...
4       emerges as something rare , an issue movie tha...
                              ...
8525    any enjoyment will be hinge from a personal th...
8526    if legendary shlockmeister ed wood had ever ma...
8527    hardly a nuanced portrait of a young woman's b...
8528      interminably bleak , to say nothing of boring .
8529    things really get weird , though not particula...
Name: text, Length: 8530, dtype: object

In [ ]:
print(y)

0       1
1       1
2       1
3       1
4       1
       ..
8525    0
8526    0
8527    0
8528    0
8529    0
Name: label, Length: 8530, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
print("Training examples:", len(X_train))
print("Testing examples:", len(X_test))

Training examples: 6824
Testing examples: 1706

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
X_train_vectorized = vectorizer.fit_transform(X_train)

In [ ]:
X_test_vectorized = vectorizer.transform(X_test)

In [ ]:
X_train_vectorized.shape

(6824, 14837)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train_vectorized, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
predictions = model.predict(X_test_vectorized)

In [ ]:
predictions[:20]

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)

Accuracy: 0.7590855803048066

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(
    classification_report(
        y_test,
        predictions
    )
)

              precision    recall  f1-score   support

           0       0.76      0.75      0.76       848
           1       0.76      0.76      0.76       858

    accuracy                           0.76      1706
   macro avg       0.76      0.76      0.76      1706
weighted avg       0.76      0.76      0.76      1706

In [ ]:
new_review = [
    "I really enjoyed this movie."
]

In [ ]:
new_review_vector = vectorizer.transform(
    new_review
)

In [ ]:
prediction = model.predict(
    new_review_vector
)

print(prediction)

[0]

In [ ]:
new_review = [
    "I am sad"
]

In [ ]:
new_review_vector = vectorizer.transform(
    new_review
)

In [ ]:
prediction = model.predict(
    new_review_vector
)

print(prediction)

[1]

In [ ]:
def predict_sentiment(review):

    review_vector = vectorizer.transform(
        [review]
    )

    prediction = model.predict(
        review_vector
    )[0]

    if prediction == 1:
        return "POSITIVE"
    else:
        return "NEGATIVE"

In [ ]:
print(
    predict_sentiment(
        "I really loved this movie!"
    )
)

NEGATIVE

In [ ]:
print(
    predict_sentiment(
        "I really loved this movie!"
    )
)

NEGATIVE

In [ ]:
print(
    predict_sentiment(
        "Happy"
    )
)

POSITIVE

In [ ]:
print(
    predict_sentiment(
        "I am sad"
    )
)

POSITIVE

In [ ]:
print(
    predict_sentiment(
        "I am dead"
    )
)

NEGATIVE

In [ ]:
model.fit(X_train_vectorized, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
import joblib

joblib.dump(model, "sentiment_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [ ]:
ds = load_dataset("cornell-movie-review-data/rotten_tomatoes")

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 8530
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
})